version: "3.8"
services:
  app:
    build: ./backend
    container_name: laravel-app
    ports:
      - "8000:80"
      - "9020:9003"  # Xdebug用ポート（ホスト側を9020に変更）
    volumes:
      - ./backend:/var/www/html
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: "client_host=host.docker.internal client_port=9003"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: tabi-search
      MYSQL_USER: shionezawa
      MYSQL_PASSWORD: Shion0423
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
